version: "3.8"

services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    ports:
      - "25565:25565/tcp"
      - "19132:19132/udp" # To Bedrock Edition
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      SERVER_NAME: "Minecraft Server Vanilla" # Name of Server
      TYPE: "VANILLA" # Use "PAPER" for better performance and features
      VERSION: "LATEST" # Use "LATEST" for the latest version or specify a version like "1.20.2"
      ONLINE_MODE: "true" # Set to false if you want to allow cracked clients
      MEMORY: "2G" # Adjust memory allocation as needed
      VIEW_DISTANCE: "10" # Adjust view distance for performance
      DIFFICULTY: "hard" # Set game difficulty (peaceful, easy, normal, hard)
      # SEED: "123456789" # Optional: Set a specific world seed
      # HARDCORE: "false" # Set to true for hardcore mode
    volumes:
      - ./minecraft-data:/data

  # playit.gg client
  playit:
    image: ghcr.io/playit-cloud/playit-agent:latest
    container_name: playit-agent
    network_mode: "host"
    environment:
      SECRET_KEY: your_secret_key_here
    volumes:
      - ./playit:/root/.playit
